# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Cyber@UC
email: cyberatuc513@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A student group at the University of Cincinnati dedicated to learning about
  and educating others on all things cybersecurity.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
lang: en_US
future: true # show future-dated posts
# refer to http://shopify.github.io/liquid/filters/date/ to customize this
date_format: "%b %-d, %Y"

# page settings
permalink: /:categories/:year/:month/:day/:title
collections:
  meetings:
    output: true
    permalink: /:collection/:name
defaults:
  - scope:
      path: ""
      type: meetings
    values:
      layout: meeting

# SOCIAL MEDIA LINKS
# Many values appear in multiple places, so if you're changing something, make
# sure you change it everywhere!
twitter:
  username: CyberAtUC
  card: summary
twitter_username: CyberAtUC
facebook_username: CyberAtUC
instagram_username: CyberAtUC
github_username: UCyber
youtube_channel_id: UCWcJuk7A_1nDj4m-cHWvIFw
rss: RSS
social:
  name: Cyber@UC
  links:
  - https://twitter.com/CyberAtUC
  - https://www.facebook.com/CyberAtUC
  - https://www.instagram.com/CyberAtUC
  - https://github.com/UCyber
  - https://youtube.com/channel/UCWcJuk7A_1nDj4m-cHWvIFw

# links to appear in the navbar
header_pages:
- about.md
- _meetings/index.html
- blog.md
- guides/index.md

# Build settings
markdown: kramdown
plugins:
  - jekyll-assets
  - bootstrap
  - font-awesome-sass
  - uglifier
  - jekyll-feed
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
